esphome:
  name: powermeter
  friendly_name: powermeter
  on_boot:
    priority: -100.0
    then:
      - delay: 2s

esp8266:
  board: nodemcu
  # arduino_version: 2.5.2

external_components:
  - source:
      type: git
      url: https://github.com/HeMan/esphome-components
    components: [hdlc]

wifi:
  ssid: !secret wifissid
  password: !secret wifipwd

logger:
  level: VERY_VERBOSE
  baud_rate: 0 # disable logging over uart

api:
  encryption:
    key: !secret encryption_key

ota:

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200


sensor:
  - platform: hdlc
    uart_id: uart_bus
    phase_1:
      voltage:
        name: "Voltage Phase 1"
      current:
        name: "Current Phase 1"
      import:
        active_power:
          name: "Momentary Active Import Phase 1"
        reactive_power:
          name: "Momentary Reactive Import Phase 1"
      export:
        active_power:
          name: "Momentary Active Export Phase 1"
        reactive_power:
          name: "Momentary Reactive Export Phase 1"
    phase_2:
      voltage:
        name: "Voltage Phase 2"
      current:
        name: "Current Phase 2"
      import:
        active_power:
          name: "Momentary Active Import Phase 2"
        reactive_power:
          name: "Momentary Reactive Import Phase 2"
      export:
        active_power:
          name: "Momentary Active Export Phase 2"
        reactive_power:
          name: "Momentary Reactive Export Phase 2"
    phase_3:
      voltage:
        name: "Voltage Phase 3"
      current:
        name: "Current Phase 3"
      import:
        active_power:
          name: "Momentary Active Import Phase 3"
        reactive_power:
          name: "Momentary Reactive Import Phase 3"
      export:
        active_power:
          name: "Momentary Active Export Phase 3"
        reactive_power:
          name: "Momentary Reactive Export Phase 3"
    momentary:
      import:
        active_power:
          name: "Momentary Active Import"
        reactive_power:
          name: "Momentary Reactive Import"
      export:
        active_power:
          name: "Momentary Active Export"
        reactive_power:
          name: "Momentary Reactive Export"
    cumulative:
      import:
        active_power:
          name: "Cumulative Active Import"
        reactive_power:
          name: "Cumulative Reactive Import"
      export:
        active_power:
          name: "Cumulative Active Export"
        reactive_power:
          name: "Cumulative Reactive Export"
